import * as THREE from 'three';
type Options={reducedMotion:boolean;onReady:()=>void;onError:()=>void};
export function mountBoard(host:HTMLElement,options:Options):()=>void{
 const mobile=matchMedia('(max-width:700px)').matches;
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:!mobile,powerPreference:'low-power'});
 renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.25:1.75));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.45;renderer.shadowMap.enabled=!mobile;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-7,7,5.7,-5.7,.1,80);camera.position.set(11,13,15);camera.lookAt(0,0,0);const board=new THREE.Group();scene.add(board);board.rotation.y=-.15;
 const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();
 const mat=(color:THREE.ColorRepresentation,metalness=.25,roughness=.6)=>{const m=new THREE.MeshStandardMaterial({color,metalness,roughness});materials.add(m);return m;};
 const gold=mat('#b99a5c',.8,.3),edge=mat('#322b21',.8,.35),black=mat('#101b1c'),road=mat('#27352f'),cream=mat('#ddd0ac',.25),emerald=mat('#2c796d',.55),violet=mat('#76608c',.45),windowMat=mat('#e7c676',.7);
 const mesh=(g:THREE.BufferGeometry,m:THREE.Material,x:number,y:number,z:number,parent:THREE.Object3D=board)=>{geometries.add(g);const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=!mobile;o.receiveShadow=!mobile;parent.add(o);return o;};
 const box=(w:number,h:number,d:number,m:THREE.Material,x:number,y:number,z:number,parent?:THREE.Object3D)=>mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,parent);
 box(9.6,.24,9.6,edge,0,-.23,0);box(9.35,.1,9.35,gold,0,-.06,0);box(9.15,.12,9.15,black,0,.03,0);
 for(const v of [-3.08,0,3.08]){box(8.9,.015,.22,road,0,.1,v);box(.22,.015,8.9,road,v,.1,0);}
 for(let i=-4;i<=4;i++)for(const v of [-3.08,3.08]){box(.2,.02,.025,gold,i,.12,v);box(.025,.02,.2,gold,v,.12,i);}
 for(let i=0;i<28;i++){const side=Math.floor(i/7),offset=(i%7-3)*1.28;const x=side===0?offset:side===1?4.02:side===2?-offset:-4.02,z=side===0?-4.02:side===1?offset:side===2?4.02:-offset;const tile=box(1.14,.08,.83,i%3===0?violet:i%3===1?emerald:cream,x,.14,z);if(side%2)tile.rotation.y=Math.PI/2;box(.13,.17,.13,gold,x,.28,z);}
 const points=[[-2.18,-2.1],[-1.17,-2.1],[1.18,-2.1],[2.15,-2.1],[-2.2,-1.04],[2.14,-.96],[-2.14,1.12],[-1.04,2.08],[1.14,2.08],[2.18,2.07],[2.13,1.06],[-2.17,2.08]];
 points.forEach(([x,z],i)=>{const h=.65+((i*7)%9)*.16,w=i%3===0?.7:.55;box(.98,.1,.98,i%2?emerald:violet,x,.17,z);box(w,h,.58,i%3===0?cream:i%3===1?emerald:violet,x,.24+h/2,z);box(w+.08,.07,.65,gold,x,.28+h,z);for(let f=0;f<Math.floor(h/.23);f++)for(let c=0;c<2;c++)box(.075,.09,.014,windowMat,x+(c-.5)*.23,.4+f*.23,z+.298);if(i%3===0){mesh(new THREE.SphereGeometry(w*.48,12,8,0,Math.PI*2,0,Math.PI/2),gold,x,.32+h,z);mesh(new THREE.ConeGeometry(.07,.34,8),gold,x,.65+h,z);}else if(i%3===1)box(.3,.25,.35,black,x,h+.4,z);});
 box(1.75,.17,1.75,gold,0,.21,0);box(1.5,.6,1.3,cream,0,.58,0);box(1.7,.1,1.5,edge,0,.92,0);for(const x of [-.49,0,.49]){box(.19,.34,.04,black,x,.53,.671);mesh(new THREE.SphereGeometry(.095,10,6,0,Math.PI*2,0,Math.PI/2),black,x,.7,.671);}mesh(new THREE.SphereGeometry(.56,20,12,0,Math.PI*2,0,Math.PI/2),gold,0,.98,0);mesh(new THREE.ConeGeometry(.06,.34,8),gold,0,1.67,0);for(const x of [-.8,.8])for(const z of [-.7,.7]){mesh(new THREE.CylinderGeometry(.09,.12,.9,8),cream,x,.7,z);mesh(new THREE.SphereGeometry(.15,10,8),gold,x,1.18,z);}
 for(let i=0;i<14;i++){const a=i/14*Math.PI*2,x=Math.cos(a)*2.7,z=Math.sin(a)*2.7;box(.045,.24,.045,edge,x,.3,z);mesh(new THREE.IcosahedronGeometry(.16,0),emerald,x,.5,z);}
 const pawn=(x:number,z:number,m:THREE.Material)=>{const g=new THREE.Group();board.add(g);g.position.set(x,.26,z);mesh(new THREE.CylinderGeometry(.19,.29,.12,16),gold,0,0,0,g);mesh(new THREE.ConeGeometry(.2,.5,16),m,0,.3,0,g);mesh(new THREE.SphereGeometry(.18,16,10),m,0,.62,0,g);return g;};const p1=pawn(-3.95,1.3,emerald),p2=pawn(2.6,4,violet);
 const dice=new THREE.Group();scene.add(dice);dice.position.set(4,.7,3.7);dice.rotation.set(.12,.25,.14);box(.68,.68,.68,cream,0,0,0,dice);const pip=(x:number,y:number,z:number,axis:string)=>{const dot=mesh(new THREE.CircleGeometry(.043,10),black,x,y,z,dice);if(axis==='top')dot.rotation.x=-Math.PI/2;if(axis==='side')dot.rotation.y=Math.PI/2;};for(const [x,z] of [[-.18,-.18],[.18,-.18],[0,0],[-.18,.18],[.18,.18]])pip(x,.342,z,'top');for(const x of [-.18,.18])for(const y of [-.18,0,.18])pip(x,y,.342,'front');pip(.342,0,0,'side');
 scene.add(new THREE.HemisphereLight('#e5d7c2','#1b2832',2));const key=new THREE.DirectionalLight('#ffdf9b',4.5);key.position.set(2,10,5);key.castShadow=!mobile;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-7,right:7,top:7,bottom:-7});key.shadow.bias=-.001;scene.add(key);const fill=new THREE.DirectionalLight('#9675ff',3);fill.position.set(-7,4,-5);scene.add(fill);const rim=new THREE.DirectionalLight('#67d8a3',2.3);rim.position.set(6,3,-7);scene.add(rim);
 let raf=0,visible=true,stopped=false,px=0,py=0,last=0;const started=performance.now();
 const draw=(now:number)=>{if(stopped)return;if(visible&&!document.hidden&&now-last>=(mobile?1000/30:1000/60)){const t=(now-started)/1000;if(!options.reducedMotion){board.rotation.y+=(-.15+px*.055-board.rotation.y)*.035;board.rotation.x+=(py*.025-board.rotation.x)*.035;dice.position.y=.8+Math.sin(t*.85)*.1;dice.rotation.set(.12+Math.sin(t*.5)*.08,t*.13,.14);p1.position.y=.26+Math.sin(t*1.3)*.025;p2.position.y=.26+Math.cos(t*1.3)*.025;}renderer.render(scene,camera);last=now;}if(!options.reducedMotion&&visible&&!document.hidden)raf=requestAnimationFrame(draw);};
 const render=()=>{cancelAnimationFrame(raf);last=-Infinity;raf=requestAnimationFrame(draw);};const resize=()=>{const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h);const aspect=w/h,half=Math.max(5.65,6.5/aspect);camera.left=-half*aspect;camera.right=half*aspect;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix();render();};const pointer=(e:PointerEvent)=>{if(e.pointerType!=='mouse')return;const r=host.getBoundingClientRect();px=(e.clientX-r.left)/r.width-.5;py=(e.clientY-r.top)/r.height-.5;};const leave=()=>{px=0;py=0;};const visibility=()=>{if(!document.hidden)render();else cancelAnimationFrame(raf);};const lost=(e:Event)=>{e.preventDefault();stopped=true;cancelAnimationFrame(raf);options.onError();};
 renderer.domElement.addEventListener('webglcontextlost',lost);host.addEventListener('pointermove',pointer);host.addEventListener('pointerleave',leave);document.addEventListener('visibilitychange',visibility);const ro=new ResizeObserver(resize);ro.observe(host);const io=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)render();else cancelAnimationFrame(raf);});io.observe(host);resize();renderer.render(scene,camera);options.onReady();
 return()=>{stopped=true;cancelAnimationFrame(raf);ro.disconnect();io.disconnect();host.removeEventListener('pointermove',pointer);host.removeEventListener('pointerleave',leave);document.removeEventListener('visibilitychange',visibility);renderer.domElement.removeEventListener('webglcontextlost',lost);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());key.shadow.dispose();renderer.dispose();renderer.domElement.remove();};
}
